
# Test basics

```{r zbmicat}

#load package
library(zanthror)
#devtools::document()
#devtools::load_all()

#load piping support
library(magrittr)
library(dplyr)

# access test data
data(zanthror_testdata)

# singular vector assignment
zbmicat_v <- zbmicat(
  bmi = zanthror_testdata$bmi,
  age = zanthror_testdata$age_years,
  gender = zanthror_testdata$gender
)
table(zbmicat_v)

# return vector to frame, traditional
zanthror_testdata$gender_char <- ifelse(zanthror_testdata$gender == 1, "M", "F")
zanthror_testdata$zbmicat <- zbmicat(
  bmi = zanthror_testdata$bmi,
  age = zanthror_testdata$age_years,
  gender = zanthror_testdata$gender_char,
  male_code = "M",
  female_code = "F"
)
table(zanthror_testdata$zbmicat)

# return vector to frame, tidyverse
zanthror_testdata %<>% 
  mutate(
    zbmicat_df = zbmicat(
      bmi = bmi,
      age = age_years,
      gender = gender,
      male_code = 1,
      female_code = 2
      )
    )
table(zanthror_testdata$zbmicat_df)

zanthror_testdata %<>% 
  mutate(
    zbmicat_haven = zbmicat(
    bmi = bmi,
    age = age_years,
    gender = gender,
    return = "haven", wtabbr = TRUE
    )
  )
table(haven::as_factor(zanthror_testdata$zbmicat_haven))

```

```{r zbmicat_lms}

# singular vector assignment
zbmicat_lms_v <- zbmicat_lms(
  bmi = zanthror_testdata$bmi,
  age = zanthror_testdata$age_years,
  gender = zanthror_testdata$gender
)
table(zbmicat_lms_v)

# return vector to frame, traditional
zanthror_testdata$gender_char <- ifelse(zanthror_testdata$gender == 1, "M", "F")
zanthror_testdata$zbmicat_lms <- zbmicat_lms(
  bmi = zanthror_testdata$bmi,
  age = zanthror_testdata$age_years,
  gender = zanthror_testdata$gender_char,
  male_code = "M",
  female_code = "F"
)
table(zanthror_testdata$zbmicat_lms)

# return vector to frame, tidyverse
library(magrittr)
library(dplyr)
zanthror_testdata %<>% 
  mutate(
    zbmicat_lms_df = zbmicat_lms(
      bmi = bmi,
      age = age_years,
      gender = gender,
      male_code = 1,
      female_code = 2
      )
    )
table(zanthror_testdata$zbmicat_lms_df)

zanthror_testdata %<>% 
  mutate(
    zbmicat_lms_haven = zbmicat_lms(
    bmi = bmi,
    age = age_years,
    gender = gender,
    return = "haven", wtabbr = TRUE
    )
  )
table(haven::as_factor(zanthror_testdata$zbmicat_lms_haven))

```

```{r}

# test the zanthro function
zanthror_testdata$testzanthro1 = zanthro(measure = zanthror_testdata$height_cm,
        xvar = zanthror_testdata$age_years,
        chart = "la", 
        version = "US",
        gender = zanthror_testdata$gender_label,
        male_code = "Male",
        female_code = "Female")

zanthror_testdata %<>%
  mutate(
    testzanthro2 = zanthro(
      measure = height_cm,
      xvar = age_years,
      chart = "la", 
      version = "US",
      gender = gender_label,
      male_code = "Male",
      female_code = "Female"
      )
    )

```

